# Generated by Django 5.2.7 on 2025-10-04 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('field_key', models.CharField(max_length=255)),
                ('data_type', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=50)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='Onboard.integrationtoken')),
            ],
        ),
    ]
