# Generated by Django 5.2.7 on 2025-10-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0002_customfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
