# Generated by Django 5.2.7 on 2025-10-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0003_customfield_is_checked'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationtoken',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationtoken',
            name='company_email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integrationtoken',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='integrationtoken',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='integrationtoken',
            name='website',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
