# Generated by Django 5.2.7 on 2025-10-07 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0004_integrationtoken_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='integrationtoken',
            name='company_email',
        ),
        migrations.CreateModel(
            name='Pdf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Onboard.integrationtoken')),
            ],
        ),
    ]
