# Generated by Django 5.2.7 on 2025-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0005_remove_integrationtoken_company_email_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrationtoken',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
    ]
