# Generated by Django 5.2.7 on 2025-10-08 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Onboard', '0006_integrationtoken_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pdf',
        ),
    ]
